= RHDH dynamic plugins 

This directory contains starter files to create a dynamic plugin wrapper for third-party backend plugin

:icons: font
:uri-dynamic-plugin-readme: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/readme.adoc#export_backend_plugin
:uri-setup-script: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/setup-wrapper.sh
:uri-backstage-new-backend-system: https://backstage.io/docs/plugins/new-backend-system/

== Plugin wrapper for backend plugin

To create a dynamic plugin wrapper for third-party backend plugin, copy the files and directories from this direcoty to an empty directory, and either run {uri-setup-script}[setup-wrapper.sh] or follow these stpes to change the files in the new directory:

[NOTE]
The script `setup-backend.sh` can be run without any arguments to see its usage.

* Copy `src/index.ts.template` to `src/index.ts`
* Replace the `THIRD_PARTY_PLUGIN_WITH_SCOPE` in `src/index.ts` with correct third-party plugin

[NOTE]
.Use of default
====
* Check the third-party plugin code to see if you need to use `alpha.ts` or `index.ts`, with index.ts being implicit export
* No change is required if the `src/index.ts` in the third-party backend plugin exports `default`, but if there is no `export default` in the `index.ts` you will have to use `alpha.ts` instead.
** Use `export {default} from 'THIRD_PARTY_PACKAGE/alpha'` instead of `export {default} from 'THIRD_PARTY_PACKAGE'` in such a case
====

* Copy `package.json.template` to `package.json`
* Replace the following with correct values, in `package.json`:

[source,options="nowrap"]
----
  "name": "@THIRD_PARTY_PLUGIN_WITHOUT_SCOPE@-wrapper",                         # <.>
  "description": "Wrapper for @THIRD_PARTY_PLUGIN_SHORT_NAME@ backend plugin",  # <.>
  "author": "@AUTHOR@",                                                         # <.>
  "dependencies":
    "@THIRD_PARTY_PLUGIN_WITH_SCOPE@": "@THIRD_PARTY_PLUGIN_VERSION@"           # <.>
  "devDependencies": {
    "@backstage/cli": "0.23.1",
    "@janus-idp/cli": "^1.7.9"                                                  # <.>
  },
  ...
  "scripts":
    ...
    "export-dynamic": "janus-cli package export-dynamic-plugin --embed-as-dependencies --embed-package @THIRD_PARTY_PLUGIN_WITH_SCOPE@"  # <.>
----
<1> Replace with your wrapper plugin name
<2> Replace with correct description for your wrapper plugin
<3> Replace with correct author name
<4> Replace with the third-party plugin and its version
<5> Version `1.7.9` of the janus-cli is in tech-preview at the moment
<6> Replace with the third-party plugin

Once the above changes are complete, follow the instructions in {uri-dynamic-plugin-readme}[Dynamic Plugins readme] to complete the configuration and installation of this dynamic plugin wrapper.


[NOTE]
====
_**In order to wrap a third-party backend plugin, the backend plugin should support the new {uri-backstage-new-backend-system}[Backstage backend system]**_
====