= RHDH setup/config
Documentation for installing and configuring RHDH plugins.

:icons: font
:note-caption: :information_source:

:url-plugins-installed: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html/administration_guide_for_red_hat_developer_hub/rhdh-installing-dynamic-plugins#rhdh-supported-plugins
:url-plugins-installed-02: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/main/admin-rhdh/#con-preinstalled-dynamic-plugins
:url-rbac: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html/administration_guide_for_red_hat_developer_hub/con-rbac-overview_admin-rhdh#con-rbac-config-permission-policies_admin-rhdh
:url-rbac-02: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/main/admin-rhdh/#con-rbac-overview_admin-rhdh


== RBAC support
Create a configMap with following config:

[source,yaml]
----
  rhdh-config-rbac.yaml: |
    permission:
      enabled: true
      rbac:
        policies-csv-file: ./rbac-policy.csv
        admin:
          users:
            - name: user:default/<YOUR_USER>
----

Create another configMap with following config:

[source,yaml]
----
  rbac-policy.csv: |
    p, role:default/guests, catalog-entity, read, allow
    p, role:default/guests, catalog.entity.create, create, allow

    g, user:default/<YOUR_USER>, role:default/guests
----

Create third configMap with following config:

[source,yaml]
----
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-rbac'
        disabled: false
        pluginConfig: {}

      - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic'
        disabled: false
        pluginConfig: {}
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      - package: './dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab'
        disabled: false
      - package: './dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic'
        disabled: false
----


Now, modify the `backstage` config to add the following:

[source,yaml]
----
  application:
    replicas: 1
    appConfig:
      configMaps:
        - name: "rhdh-config"
        - name: "rhdh-config-rbac.yaml"                     # <.>
      mountPath:  /opt/app-root/src
    dynamicPluginsConfigMapName: rhdh-dynamic-plugins       # <.>
    extraFiles:                                             # <.>
        configMaps:
          - name: rhdh-config-rbac-policy
----
<1> Add the configMap for our `rbac`.
<2> Add the reference to load the dynamic plugins
<3> Add configMap for rbac policy to be mounted


== GitLab auth support
Modify the existing app-config with following config:

[source,yaml]
----
  app-config.simple.yml: |
    app:
      title: "RHDH AppEng Demo"
      baseUrl: ${HOST_URL}                                      # <.>
    backend:
      baseUrl: "${HOST_URL}"                                    # <.>
      cors:
        origin: "${HOST_URL}"                                   # <.>
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"
    signInPage: gitlab                                          # <.>
    auth:
      environment: development
      providers:
        gitlab:                                                 # <.>
          development:
            clientId: ${AUTH_GITLAB_CLIENT_ID}
            clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
            audience: ${GITLAB_HOST}
----
<1> Set the application baseUrl to host url
<2> Add the same host url as backend baseUrl. This should also show the `Administration` link
<3> Set the `cors` origin to host url
<4> Make `GitLab` show up on the sign-in / login page
<5> Add `gitlab` provider with correct config


Create secrets for:
* AUTH_GITLAB_CLIENT_ID
* AUTH_GITLAB_CLIENT_SECRET
* GITLAB_HOST

