= Dynamic wrapper for DevTools plugin
:icons: font
:note-caption: :information_source:
:uri-devtools: https://github.com/backstage/backstage/tree/v1.23.4/plugins/devtools
:uri-app-config: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/devtools/app-config-devtools.yaml
:uri-export-frontend-plugin: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins#export_frontend_plugin
:uri-export-frontend-plugin-local: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins#export_frontend_plugin_local

This directory contains files to create a dynamic plugin wrapper for the {uri-devtools}[DevTools] plugin

== Steps

To create a dynamic plugin wrapper for DevTools plugin, copy the files present in this directory in a local directory and run the following commands:

[source="bash",options="nowrap"]
----
  yarn install
  yarn export-dynamic
----

This wrapper can be tested in RHDH or locally. To test it, following steps should be performed:

. To test in RHDH instance
** Follow {uri-export-frontend-plugin}[these instructions] to export this dynamic wrapper
** Add the following content to a configMap:

[source="yaml",options="nowrap"]
----
# RHDH configuration
# Frontned plugin configuration: provides the DevTools information in the "Overview" tab as well as from a link in the Sidebar
  plugins:
    # ...
    # Existing dynamic packages
    # ...

    - package: '<Location_of_DevTools_wrapper>'
      disabled: false
      integrity: 'DevTools_WRAPPER_HASH'
      pluginConfig:
        dynamicPlugins:
          frontend:
            devtools-wrapper:
              dynamicRoutes:
                - importName: DevToolsPage
                  menuItem:
                    text: DevTools
                    icon: chat
                  path: /devtools                
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: DevToolsPage
                  config:
                    layout:
                      gridColumn: "1 / -1"
                      width: 50vw
----

[start=2]
. To test in Janus local instance
** Follow {uri-export-frontend-plugin-local}[these instructions] to export this dynamic wrapper
** Add the following content to app-config yaml:

[source="yaml",options="nowrap"]
----
# Local Janus configuration
# Frontned plugin configuration: provides the DevTools information in the "Overview" tab as well as from a link in the Sidebar
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    devtools-wrapper:
      dynamicRoutes:
        - importName: DevToolsPage
          menuItem:
            text: DevTools
            icon: chat
          path: /devtools
      mountPoints:
        - mountPoint: entity.page.overview/cards
          importName: DevToolsPage
          config:
            layout:
              gridColumn: "1 / -1"
              width: 50vw
----

After the restart of RHDH (or Janus local), you should see the DevTools contents in the **Overview** tab of your entity as well as using the Sidebar link.

[NOTE]
====
_**The config provided above is also given in {uri-app-config}[DevTools app config]**_
====