= RHDH dynamic plugins
:icons: font
:note-caption: :information_source:
:toc:
:toclevels: 5

:uri-dynamic-plugins: https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#frontend-layout-configuration
:uri-dynamic-plugin-fe-starter-files: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/frontend-wrapper-starter
:uri-dynamic-plugin-be-starter-files: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/backend-wrapper-starter
:uri-backstage-new-backend-system: https://backstage.io/docs/plugins/new-backend-system/
:uri-mountpoints: https://github.com/janus-idp/backstage-showcase/blob/main/dynamic-plugins.default.yaml#L207-L222
:uri-backstage-create-new-app: https://backstage.io/docs/getting-started/#1-create-your-backstage-app
:uri-backstage-create-new-version: https://github.com/backstage/backstage/blob/25b8e7b2597e65fb033076188ce6a9d3dec3ec11/packages/create-app/package.json#L4
:uri-janus-backstage-version: https://github.com/janus-idp/backstage-showcase/blob/main/backstage.json

Documentation for creating and testing dynamic plugins. It provides instructions on configuring the dynamic plugins on OCP as well as testing them in your local Janus-IDP showcase instance.

== Prerequisites
The following prerequites should be met before creating a wrapper for third-party plugins or to convert existing custom plugins to dynamic plugins:

. Create a new app using npx as mentioned using the following command:
----
npx @backstage/create-app@0.5.11
----

[NOTE]
====
_RHDH 1.1 is based on backstage version `1.23.4`, which uses `0.5.11` of create-app._

_**Steps needed to convert a custom plugin to dynamic as well as create wrapper for any third-party plugin will be performed in the backstage app**_
====

[start=2]
. Clone the Janus-IDP showcase repo for local testing/configuration
.. _This repo will be used to test the dynamic plugins locally before deploying them in RHDH_

[start=3]
. Install the RHDH instance using the Operator (for testing/configuring on OCP).


== Dynamic plugin wrapper
To add dynamic plugin support to a third-party plugin, a wrapper plugin can be created. This wrapper plugin will:

* Create a starter package
* import the third-party plugin as a dependency
* Modify `package.json`
* Modify `src/index.ts`
* Export the third-party plugin as a dynamic plugin

The wrapper plugin can be used to add dynamic support to either a frontend or backend plugin. There are small differences between wrapping the two.

'''

=== Dynamic plugin wrapper for third-party frontend plugin   [[wrapper_frontend_plugin]]

You can create dynamic plugin support for a third-party frontend plugin with or without starter files. To use the starter files, follow {uri-dynamic-plugin-fe-starter-files}[Dynamic plugin wrapper for frontend - instructions]. If you do not want to use starter files, complete the following steps:

. Create a starter package:
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

[start=2]
. Create `src/index.ts` file with the following content:
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export * from '<THIRD_PARTY_PLUGIN>';
----

[start=3]
. Create `app-config.yaml` file with the following content:
[source, yaml]
----
app:
  baseUrl: "https://bogussite.com"
----
_This config is needed for export-dynamic command to work and a Jira is already open to have this requirement removed. Change the baseUrl to whatever value you prefer._

[start=4]
. Modify `package.json` and add the following config if not already present in the file:

[source]
----
  "backstage": {
    "role": "frontend-plugin"
  },
  "dependencies": {
    "<THIRD_PARTY_PLUGIN>": "<THIRD_PARTY_PLUGIN_VERSION>",             # <.>
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@backstage/cli": "0.23.1",                                         # <.>
    "@janus-idp/cli": "^1.7.10"                                         # <.>
  },
  "files": [
    "dist"                                                              # <.>
    "dist-scalprum"                                                     # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "clean-dynamic-sources": "yarn clean && rm -Rf node_modules",
    "export-dynamic": "janus-cli package export-dynamic-plugin"         # <.>
  },
----
<1> add third-party plugin dependency
<2> add `@backstage/cli` as devDependency
<3> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<4> add `dist` to the package files list
<5> add `dist-scalprum` to the package files list
<6> add `export-dynamic` to scripts


==== Export the plugin for deploying to RHDH instance       [[export_frontend_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn export-dynamic                                                     # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                       # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
FRONTEND_INTEGRITY_HASH=$(npm pack --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Frontend plugin integrity Hash: $FRONTEND_INTEGRITY_HASH"    # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                          # <.>
----
<1> export the plugin as a dynamic plugin
<2> Env variable to point to the directory that will contain the dynamic plugin tgz files
<3> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<4> Lists the directory to show you the contents of output directory

Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

[NOTE]
====
_You might need to add the devDependencies if `yarn export-dynamic` throws an error like given below:_
```
Module not found: Error: Can't resolve '<DEPENDENCY>' in ...
```

_Once the dependency is added, re-run `yarn install` before running `yarn export-dynamic`_
====


==== Export the plugin for deploying to local Janus instance

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
yarn install
yarn export-dynamic --dev    # <.>
----
<1> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your project directory.

'''

=== Dynamic plugin wrapper for third-party backend plugin       [[wrapper_backend_plugin]]

You can create dynamic plugin support for a third-party backend plugin with or without starter files. To use the starter files, follow {uri-dynamic-plugin-be-starter-files}[Dynamic plugin wrapper for backend - instructions]. If you do not want to use starter files, complete the following steps:

[NOTE]
====
_**In order to wrap a third-party backend plugin, the backend plugin should support the new {uri-backstage-new-backend-system}[Backstage backend system]**_
====

. Create a starter package:
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

[start=2]
. Create `src/index.ts` file with the following content:
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export {default} from '<THIRD_PARTY_PLUGIN>';
----

[NOTE]
.Use of default
====
* The new backend system standard entrypoint (created using createBackendPlugin() or createBackendModule()) should be exported as the default export of either the main package or of an alpha package (if the new backend support is still provided as alpha APIs)
** Check the third-party plugin code to see if you need to use `alpha.ts` or `index.ts`, with index.ts being implicit export
** No change is required if the `src/index.ts` in the third-party backend plugin exports `default`, but if there is no `export default` in the `index.ts` you will have to use `alpha.ts` instead.
*** Use `export {default} from 'THIRD_PARTY_PACKAGE/alpha'` instead of `export {default} from 'THIRD_PARTY_PACKAGE'` in such a case
====

[start=3]
. Modify `package.json` and add the following config if not already present in the file:

[source,options="nowrap"]
----
  "devDependencies": {
    "@janus-idp/cli": "^1.7.10"                         # <.>
  },
  "files": [
    "dist"                                              # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "export-dynamic": "janus-cli package export-dynamic-plugin --embed-as-dependencies --embed-package <THIRD_PARTY_PLUGIN>"   # <.>
  }
----
<1> add `@janus-idp/cli` dependency, which provides a new, required, `export-dynamic-plugin` command. _Version `1.7.10` of the janus-cli is in tech-preview at the moment. If you're unsure of using this version then use an older version, e.g. `1.7.10`_
<2> add `dist` to the package files list
<3> add `export-dynamic` to scripts. This will also embedd the dependencies as well as the third party package. _If using another version of janus-cli other than `1.7.10`, remove the `--embed-as-dependencies` argument from `export-dynamic` script_
  

==== Export the plugin for deploying to RHDH instance           [[export_backend_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn tsc
yarn export-dynamic                                                 # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                   # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
BACKEND_INTEGRITY_HASH=$(npm pack ./dist-dynamic --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Backend plugin integrity Hash: $BACKEND_INTEGRITY_HASH"  # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                      # <.>
----
<1> export the plugin as a dynamic plugin
<2> Env variable to point to the directory that will contain the dynamic plugin tgz files
<3> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<4> Lists the directory to show you the contents of output directory


Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
yarn install
yarn tsc
yarn export-dynamic --dev    # <.>
----
<1> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your project directory.


== Dynamic custom plugin                   [[custom_dynamic_plugin]]
To convert a custom plugin into a dynamic plug, following steps have to be performed:

* Make sure the **create new app** prerequisite is met
* Add `export-dynamic` to `scripts`
* Add `janus-cli` to `devDependencies`
* Add `dist-scalprum` to `files` for frontend plugin only
* Convert the backend plugin to the new backend system

=== Dynamic Frontend custom plugin         [[custom_frontend_dynamic_plugin]]
To convert a frontend custom plugin into a dynamic plugin, complete the following step:

* Modify `package.json` and add the following config if not already present in the file:
[source]
----
  "devDependencies": {
    ...
    "@janus-idp/cli": "^1.7.10"                                   # <.>
  },
  "files": [
    "dist"
    "dist-scalprum"                                               # <.>
  ],
  "scripts": {
    ...
    "export-dynamic": "janus-cli package export-dynamic-plugin"   # <.>
  },
----
<1> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<2> add `dist-scalprum` to the package files list
<3> add `export-dynamic` to scripts


==== Export the frontend plugin for deploying to RHDH instance       [[export_frontend_custom_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn export-dynamic                                                     # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                       # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
FRONTEND_INTEGRITY_HASH=$(npm pack --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Frontend plugin integrity Hash: $FRONTEND_INTEGRITY_HASH"    # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                          # <.>
----
<1> export the plugin as a dynamic plugin
<2> Env variable to point to the directory that will contain the dynamic plugin tgz files
<3> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<4> Lists the directory to show you the contents of output directory

Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance    [[custom_frontend_plugin_local_run]]

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands in your frontned custom plugin directory:
[source, bash]
----
export LOCAL_DYNAMIC_PLUGIN_ROOT_DIR=<JANUS_SHOWCASE_DIR>/dynamic-plugins-root    # <.>
yarn install
yarn export-dynamic --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR   # <.>

ls -l $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR
----
<1> Environment variable to point to the local dynamic-plugin-root directory that should be in the Janus Showcase root directory
<2> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your showcase directory to be able to run/test it locally

[NOTE]
====
_Above commands should be run in the frontned plugin directory inside the Backstage app that is created initially_

_**Do not create the symbolic link manually as that will take the node_modules from the symlink directory instead of the showcase and can cause issues at runtime**_

For configuration of the frontend plugin via app-config, the plugin name can be taken from `dist-scalprum/plugin-manifest.json` file after running `export-dynamic` script
====


'''

=== Dynamic Backend plugin         [[custom_backend_dynamic_plugin]]


== Test the dynamic plugin on OCP [[deploy_dynamic_plugins]]

To test out the dynamic plugin (irrespective of whether it is a wrapper for third-party plugin or custom plugin), follow the instructions given below.

=== Create new app for plugin registry

If these commands have already been executed earlier (for another dynamic plugin) then simply run the step given in <<refresh_registry>>

[source,bash,options="nowrap"]
----
oc project <YOUR_PROJECT_OR_NAMESPACE>
oc new-build httpd --name=plugin-registry --binary                          # <.>
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
oc new-app --image-stream=plugin-registry                                   # <.>
----
<1> Creates a new build configuration
<2> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source. _The `DYNAMIC_PLUGIN_ROOT_DIR` env variable should be set before running this command_
<3> Creates a new app using the plugin-registry build

[NOTE]
.During testing
====
. _You can set an environment variable `SKIP_INTEGRITY_CHECK=true` if you prefer to not use the integrity hash, or want to quickly test changes in your plugin._
. _Setting `integrity` for the dynamic plugin can be skipped once this environment variable is set_
====


'''

=== Update dynamic plugin configMap

Modify the dynamic plugins configMap by adding the following config:
[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      <EXISTING_DYNAMIC_PLUGINS>
      - package: 'http://plugin-registry:8080/<NAME_OF_YOUR_DYNAMIC_PLUGIN_N_VERSION>.tgz'    # <.>
        disabled: false
        integrity: '<INTEGRITY_HASH_VALUE_FROM_npm_pack_command>'                             # <.>
        pluginConfig:
          dynamicPlugins:
            frontend:                                                                         # <.>
              <NAME_OF_YOUR_DYNAMIC_PLUGIN>:                                                  # <.>
                dynamicRoutes:
                  - importName: <THIRD_PARTY_COMPONENT>                                       # <.>
                    menuItem:
                      text: <THIRD_PARTY_>                                                    # <.>
                    path: /<UNIQUE_PATH>                                                      # <.>
----
<1> <WrapperPluginName>-<WrapperPluginVersion>.tgz - file that was created with `npm pack` command (prefixed with `http://plugin-registry:8080` - this is where the plugin-registry app is running)
<2> Integrity hash generated from `npm pack` output
<3> Configuration for the third-party frontned plugin
<4> Name of the wrapper plugin
<5> Component name of the third party plugin. Defauls to the `export` in index.ts
<6> Sidebar menu item text
<7> Unique path in the app

'''

=== Refresh plugin registry    [[refresh_registry]]

For any updates to this plugin, or if you add more dynamic plugins, run the following command:

[source,bash,options="nowrap"]
----
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
----
<1> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source


== Local testing configuration

For testing the dynamic plugins locally, follow the instructions given below.

Add the following config to `app-config.local.yaml` to allow dynamic plugins to be read and configured for local testing:

[source, yaml]
----
app:                                                                                                                           
  title: Janus IDP Backstage Showcase - Dynamic plugins
  baseUrl: http://localhost:3000

proxy:
 skipInvalidProxies: true
 endpoints: {}

dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    <FRONTEND_DYNAMIC_PLUGIN_NAME>:
      dynamicRoutes:
        - importName: <THIRD_PARTY_PLUGIN_COMPONENT>
          menuItem:
            text: "<TEXT_2_DISPLAY_IN_SIDEBAR>"
            icon: "<ICON_FOR_MENU_IN_SIDEBAR>"
          path: /<UNIQUE_PATH>
...
...
----

Configuration for most of the backend plugins will go in the above config yaml but in their own respective sections.

== References

* {uri-dynamic-plugins}[RHDH - Dynamic plugin doc] +
* {uri-mountpoints}[RHDH - Dynamic plugin - mountpoints example] +
* {uri-backstage-create-new-app}[Backstage - create new app] +
* {:uri-backstage-create-new-version}[Backstage - create new app version compatible with RHDH 1.1] +
* {:uri-janus-backstage-version}[RHDH 1.1 - backstage version] +
* {uri-backstage-new-backend-system}[Backstage new backend system] +
