= RHDH dynamic plugins
:icons: font
:note-caption: :information_source:
:toc:
:toclevels: 5

:url-dynamic-plugins: https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#frontend-layout-configuration
:uri-dynamic-plugin-fe-starter-files: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/frontend-wrapper-starter
:uri-dynamic-plugin-be-starter-files: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/backend-wrapper-starter
:uri-backstage-new-backend-system: https://backstage.io/docs/plugins/new-backend-system/

Documentation for creating and testing dynamic plugins. It provides instructions on configuring the dynamic plugins on OCP as well as testing them in your local Janus-IDP showcase instance.

== Prerequisites
Install the RHDH instance using the Operator (for testing/configuring on OCP) or clone the Janus-IDP showcase repo (for local testing/configuration).

== Dynamic plugin wrapper
To add dynamic plugin support to a third-party plugin, a wrapper plugin can be created. This wrapper plugin will:

* Create a starter package
* import the third-party plugin as a dependency
* Modify `package.json`
* Modify `src/index.ts`
* Export the third-party plugin as a dynamic plugin

The wrapper plugin can be used to add dynamic support to either a frontend or backend plugin. There are small differences between wrapping the two.

'''

=== Dynamic plugin wrapper for third-party frontend plugin   [[wrapper_frontend_plugin]]
To create a dynamic plugin support to a third-party frontend plugin, you'll need to either follow the steps given below:

[NOTE]
_You can take the starter files from {uri-dynamic-plugin-fe-starter-files}[Dynamic plugin wrapper for frontend - starter files] and copy them to an empty directory_

* Create a starter package (_**not needed if using frontend starter files**_):
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

* Create `src/index.ts` file with the following content (_**not needed if using frontend starter files**_):
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export * from '<THIRD_PARTY_PLUGIN>';
----

* Create `app-config.yaml` file with the following content (_**not needed if using frontend starter files**_):
[source, yaml]
----
app:
  baseUrl: "https://bogussite.com"
----
_This config is needed for export-dynamic command to work and a Jira is already open to have this requirement removed. Change the baseUrl to whatever value you prefer._

* Modify `package.json` and add the following config if not already present in the file (_**not needed if using frontend starter files**_):

[source]
----
  "backstage": {
    "role": "frontend-plugin"
  },
  "dependencies": {
    "<THIRD_PARTY_PLUGIN>": "<THIRD_PARTY_PLUGIN_VERSION>",            # <.>
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@backstage/cli": "0.23.1",                                         # <.>
    "@janus-idp/cli": "^1.4.7"                                          # <.>
  },
  "files": [
    "dist"                                                              # <.>
    "dist-scalprum"                                                     # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "clean-dynamic-sources": "yarn clean && rm -Rf node_modules",
    "export-dynamic": "janus-cli package export-dynamic-plugin"         # <.>
  },
----
<1> add third-party plugin dependency
<2> add `@backstage/cli` as devDependency
<3> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<4> add `dist` to the package files list
<5> add `dist-scalprum` to the package files list
<6> add `export-dynamic` to scripts

[NOTE]
====
_You might need to add the devDependencies if `yarn export-dynamic` throws an error like given below:_
```
Module not found: Error: Can't resolve '<DEPENDENCY>' in ...
```

_Once the dependency is added, please re-run `yarn install` before running `yarn export-dynamic`_
====

==== Export the plugin for deploying to RHDH instance

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn export-dynamic                                # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root  # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
INTEGRITY_HASH=$(npm pack --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  # <.>

echo "Integrity Hash: $INTEGRITY_HASH"             # <.>
ls -l $DYNAMIC_PLUGIN_ROOT_DIR                     # <.>
----
<1> export the plugin as a dynamic plugin
<2> Env variable to point to the directory that will contain the dynamic plugin tgz files
<3> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir
<4> Displays the integrity hash. This value will be needed later on when adding this dynamic plugin to the configMap
<5> Lists the directory to show you the contents of output directory

Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
yarn install
yarn export-dynamic --dev    # <.>
----
<1> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your project directory.

'''

=== Dynamic plugin wrapper for third-party backend plugin       [[wrapper_backend_plugin]]
To create a dynamic plugin support to a third-party backend plugin, you'll need to either follow the steps given below:

[NOTE]
====
. _You can take the starter files from {uri-dynamic-plugin-be-starter-files}[Dynamic plugin wrapper for backend - starter files] and copy them to an empty directory_
. _**In order to wrap a third-party backend plugin, the backend plugin should support the new {uri-backstage-new-backend-system}[Backstage backend system]**_
====

* Create a starter package (_**not needed if using backend starter files**_):
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

* Create `src/index.ts` file with the following content (_**not needed if using backend starter files**_):
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export {default} from '<THIRD_PARTY_PLUGIN>';
----

* Modify `package.json` and add the following config if not already present in the file (_**not needed if using backend starter files**_):

[source,options="nowrap"]
----
  "dependencies": {
    "@backstage/backend-dynamic-feature-service": "0.1.0",              # <.>
  }
  "devDependencies": {
    "@janus-idp/cli": "^1.7.7"                                          # <.>
  },
  "files": [
    "dist-dynamic/*.*",                                                 # <.>
    "dist-dynamic/dist/**",                                             # <.>
    "dist-dynamic/alpha/*"                                              # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "clean-dynamic-sources": "yarn clean && rm -Rf node_modules dist-dynamic",
    "export-dynamic": "janus-cli package export-dynamic-plugin --embed-as-dependencies --embed-package <THIRD_PARTY_PLUGIN>"   # <.>
  }
----
<1> add dependency for `@backstage/backend-dynamic-feature-service`
<2> add `@janus-idp/cli` dependency, which provides a new, required, `export-dynamic-plugin` command. _Version `1.7.7` of the janus-cli is in tech-preview at the moment. If you're unsure of using this version then please use an older version, e.g. `1.4.7`_
<3> add `dist-dynamic/*.*` to the package files list
<4> add `dist-dynamic/dist/**` to the package files list
<5> add `dist-dynamic/alpha/*` to the package files list
<6> add `export-dynamic` to scripts. This will also embedd the dependencies as well as the third party package. _If using another version of janus-cli other than `1.7.7`, please remove the `--embed-as-dependencies` argument from `export-dynamic` script_
  

==== Export the plugin for deploying to RHDH instance

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn tsc
yarn export-dynamic                                       # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root         # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
INTEGRITY_HASH=$(npm pack ./dist-dynamic --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  # <.>

echo "Integrity Hash: $INTEGRITY_HASH"                    # <.>
ls -l $DYNAMIC_PLUGIN_ROOT_DIR                            # <.>
----
<1> export the plugin as a dynamic plugin
<2> Env variable to point to the directory that will contain the dynamic plugin tgz files
<3> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir
<4> Displays the integrity hash. This value will be needed later on when adding this dynamic plugin to the configMap
<5> Lists the directory to show you the contents of output directory


Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
yarn install
yarn tsc
yarn export-dynamic --dev    # <.>
----
<1> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your project directory.


== Dynamic plugin - WIP   [[custom_dynamic_plugin]]
To add dynamic plugin support to a third-party plugin, a wrapper plugin can be created. This wrapper plugin will:

* import the third-party plugin as a dependency.
* include the additions to the package.json and src/dynamic/index.ts file as described above.
* export it as a dynamic plugin.

== Test the dynamic plugin on OCP [[deploy_dynamic_plugins]]

To test out the dynamic plugin (irrespective of whether it is a wrapper for third-party plugin or custom plugin), please
follow the instructions given below.

=== Create new app for plugin registry

If these commands have already been executed earlier (for another dynamic plugin) then simply run the step given in <<refresh_registry>>

[source,bash,options="nowrap"]
----
oc project <YOUR_PROJECT_OR_NAMESPACE>
oc new-build httpd --name=plugin-registry --binary                          # <.>
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
oc new-app --image-stream=plugin-registry                                   # <.>
----
<1> Creates a new build configuration
<2> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source. _The `DYNAMIC_PLUGIN_ROOT_DIR` env variable should be set before running this command_
<3> Creates a new app using the plugin-registry build

[NOTE]
.During testing
====
. _You can set an environment variable `SKIP_INTEGRITY_CHECK=true` if you prefer to not use the integrity hash, or want to quickly test changes in your plugin._
. _Setting `integrity` for the dynamic plugin can be skipped once this environment variable is set_
====


'''

=== Update dynamic plugin configMap

Modify the dynamic plugins configMap by adding the following config:
[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      <EXISTING_DYNAMIC_PLUGINS>
      - package: 'http://plugin-registry:8080/<NAME_OF_YOUR_DYNAMIC_PLUGIN>.tgz'    # <.>
        disabled: false
        integrity: '<INTEGRITY_HASH_VALUE_FROM_npm_pack_command>'                   # <.>
        pluginConfig:
          dynamicPlugins:
            frontend:                                                               # <.>
              <NAME_OF_YOUR_DYNAMIC_PLUGIN>:                                        # <.>
                dynamicRoutes:
                  - importName: <THIRD_PARTY_COMPONENT>                             # <.>
                    menuItem:
                      text: <THIRD_PARTY_>                                          # <.>
                    path: /<UNIQUE_PATH>                                            # <.>
----
<1> tgz file name that was created with `npm pack` command (prefixed with `http://plugin-registry:8080` - this is where our plugin-registry app is running)
<2> Integrity hash generated from `npm pack` output
<3> Configuration for the third-party frontned plugin
<4> Name of the wrapper plugin
<5> Component name of the third party plugin. Defauls to the `export` in index.ts
<6> Sidebar menu item text
<7> Unique path in the app

'''

=== Refresh plugin registry    [[refresh_registry]]

For any updates to this plugin, or if you add more dynamic plugins, please run the following command:

[source,bash,options="nowrap"]
----
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
----
<1> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source


== Local testing configuration

For testing the dynamic plugins locally, please follow the instructions given below.

Add the following config to `app-config.local.yaml` to allow dynamic plugins to be read and configured for local testing:

[source, yaml]
----
app:                                                                                                                           
  title: Janus IDP Backstage Showcase - Dynamic plugins
  baseUrl: http://localhost:3000

proxy:
 skipInvalidProxies: true
 endpoints: {}

dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    <FRONTEND_DYNAMIC_PLUGIN_NAME>:
      dynamicRoutes:
        - importName: <THIRD_PARTY_PLUGIN_COMPONENT>
          menuItem:
            text: "<TEXT_2_DISPLAY_IN_SIDEBAR>"
            icon: "<ICON_FOR_MENU_IN_SIDEBAR>"
          path: /<UNIQUE_PATH>
...
...
----

Configuration for most of the backend plugins will go in the above config yaml but in their own respective sections.

== References

* {url-dynamic-plugins}[RHDH - Dynamic plugin doc] +
* {uri-backstage-new-backend-system}[Backstage new backend system] +
