= RHDH dynamic plugins
:icons: font
:note-caption: :information_source:
:toc:
:toclevels: 5

:uri-dynamic-plugins: https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#frontend-layout-configuration
:uri-dynamic-plugin-fe-starter-files: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/frontend-wrapper-starter
:uri-backstage-dynamic-loading-template: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/backend-plugin.ts.template
:uri-backstage-dynamic-loading-example: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/samples/custom/hello-world-backend/src/plugin.ts
:uri-backstage-dynamic-loading-index: https://github.com/sgahlot/rhdh-op-config/blob/6426b3a03deea14316453cdfa6c6a476c8a2cbc1/dynamic-plugins/samples/custom/hello-world-backend/src/index.ts#L3
:uri-backstage-new-backend-system: https://backstage.io/docs/plugins/new-backend-system/
:uri-mountpoints: https://github.com/janus-idp/backstage-showcase/blob/main/dynamic-plugins.default.yaml#L207-L222
:uri-rhdh-mountpoints: https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#using-mount-points
:uri-backstage-create-new-app: https://backstage.io/docs/getting-started/#1-create-your-backstage-app
:uri-backstage-create-new-version: https://github.com/backstage/backstage/blob/25b8e7b2597e65fb033076188ce6a9d3dec3ec11/packages/create-app/package.json#L4
:uri-janus-backstage-version: https://github.com/janus-idp/backstage-showcase/blob/main/backstage.json
:uri-backend-plugin-template: https://github.com/janus-idp/backstage-showcase/blob/main/backstage.json
:uri-icons: https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#extend-internal-library-of-available-icons
:uri-icons-systen-internal: https://github.com/backstage/backstage/blob/master/packages/app-defaults/src/defaults/icons.tsx
:uri-custom-icon-exported-ex: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/bazaar/src/index.ts#L1
:uri-custom-icon-use-ex-1: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/bazaar/app-config-bazaar.yaml#L10
:uri-custom-icon-use-ex-2: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/bazaar/app-config-bazaar.yaml#L11
:uri-custom-icon-use-ex-3: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/bazaar/app-config-bazaar.yaml#L16
:uri-system-icon-use-ex: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/devtools/app-config-devtools.yaml#L13



Documentation for creating and testing dynamic plugins. It provides instructions on configuring the dynamic plugins on OCP as well as testing them in your local Janus-IDP showcase instance.

== Prerequisites
The following prerequites should be met before creating a wrapper for third-party plugins or to convert existing custom plugins to dynamic plugins:

. Create a new app using npx as mentioned using the following command:
----
npx @backstage/create-app@0.5.11
----

[NOTE]
====
_RHDH 1.1 is based on backstage version `1.23.4`, which uses `0.5.11` of create-app._

_**Steps needed to convert a custom plugin to dynamic, as well as to create wrapper for any third-party plugin, will be performed in the backstage app**_
====

[start=2]
. Clone the Janus-IDP showcase repo for local testing/configuration
.. _This repo will be used to test the dynamic plugins locally before deploying them in RHDH_

[start=3]
. Install the RHDH instance using the Operator (for testing/configuring on OCP).


== Dynamic plugin wrapper
To add dynamic plugin support to a third-party plugin, a wrapper plugin can be created. This wrapper plugin will:

* Create a starter package
* import the third-party plugin as a dependency
* Modify `package.json`
* Modify `src/index.ts`
* Export the third-party plugin as a dynamic plugin

The wrapper plugin can be used to add dynamic support to either a frontend or backend plugin. There are small differences between wrapping the two.

'''

=== Dynamic plugin wrapper for third-party frontend plugin   [[wrapper_frontend_plugin]]

You can create dynamic plugin support for a third-party frontend plugin with or without starter files. To use the starter files, follow {uri-dynamic-plugin-fe-starter-files}[Dynamic plugin wrapper for frontend - instructions]. If you do not want to use starter files, complete the following steps:

. Create a starter package:
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

[start=2]
. Create `src/index.ts` file with the following content:
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export * from '<THIRD_PARTY_PLUGIN>';
----

[start=3]
. Create `app-config.yaml` file with the following content:
[source, yaml]
----
app:
  baseUrl: "https://bogussite.com"
----
_This config is needed for export-dynamic command to work and a Jira is already open to have this requirement removed. Change the baseUrl to whatever value you prefer._

[start=4]
. Modify `package.json` and add the following config if not already present in the file:

[source]
----
  "backstage": {
    "role": "frontend-plugin"
  },
  "dependencies": {
    "<THIRD_PARTY_PLUGIN>": "<THIRD_PARTY_PLUGIN_VERSION>",             # <.>
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@backstage/cli": "0.23.1",                                         # <.>
    "@janus-idp/cli": "^1.7.10"                                         # <.>
  },
  "files": [
    "dist"                                                              # <.>
    "dist-scalprum"                                                     # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "clean-dynamic-sources": "yarn clean && rm -Rf node_modules",
    "export-dynamic": "janus-cli package export-dynamic-plugin"         # <.>
  },
----
<.> add third-party plugin dependency
<.> add `@backstage/cli` as devDependency
<.> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<.> add `dist` to the package files list
<.> add `dist-scalprum` to the package files list
<.> add `export-dynamic` to scripts


==== Export the plugin for deploying to RHDH instance       [[export_frontend_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn export-dynamic                                                     # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                       # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
FRONTEND_INTEGRITY_HASH=$(npm pack --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Frontend plugin integrity Hash: $FRONTEND_INTEGRITY_HASH"    # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                          # <.>
----
<.> Export the plugin as a dynamic plugin
<.> Env variable to point to the directory that will contain the dynamic plugin tgz files
<.> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<.> Lists the directory to show you the contents of output directory

Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

[NOTE]
====
_You might need to add the devDependencies if `yarn export-dynamic` throws an error like given below:_
```
Module not found: Error: Can't resolve '<DEPENDENCY>' in ...
```

_Once the dependency is added, re-run `yarn install` before running `yarn export-dynamic`_
====


==== Export the plugin for deploying to local Janus instance        [[export_frontend_plugin_local]]

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
export LOCAL_DYNAMIC_PLUGIN_ROOT_DIR=<JANUS_SHOWCASE_DIR>/dynamic-plugins-root     # <.>
yarn install
yarn export-dynamic --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR    # <.>
----
<.> Environment variable to point to the local dynamic-plugin-root directory that should be in the Janus Showcase root directory
<.> Export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your showcase directory to be able to run/test it locally

[NOTE]
====
_Above commands should be run in the frontend plugin directory inside the Backstage app that is created initially_

_**Do not create the symbolic link manually as that will take the node_modules from the symlink directory instead of the showcase and can cause issues at runtime**_
====


'''

=== Dynamic plugin wrapper for third-party backend plugin       [[wrapper_backend_plugin]]

You can create dynamic plugin support for a third-party backend plugin with or without starter files. To use the starter files, follow {uri-dynamic-plugin-be-starter-files}[Dynamic plugin wrapper for backend - instructions]. If you do not want to use starter files, complete the following steps:

[NOTE]
====
_In order to wrap a third-party backend plugin, the backend plugin should support the new {uri-backstage-new-backend-system}[Backstage backend system]_

_**If the third-party backend plugin does not support the new Backstage backend system, follow the instructions given in <<add_dynamic_loading_entrypoint>> so that the wrapper can be exported as dynamic plugin**_
====

. Create a starter package:
[source, bash]
----
yarn set version classic
yarn init
# provide the values prompted
----

[start=2]
. Create `src/index.ts` file with the following content:
[source, yaml]
----
# The dynamicPluginInstaller entry point must be exported in the main src/index.ts file:
export {default} from '<THIRD_PARTY_PLUGIN>';
----

[NOTE]
.Use of default
====
* The new backend system standard entrypoint (created using createBackendPlugin() or createBackendModule()) should be exported as the default export of either the main package or of an alpha package (if the new backend support is still provided as alpha APIs)
** Check the third-party plugin code to see if you need to use `alpha.ts` or `index.ts`, with index.ts being implicit export
** No change is required if the `src/index.ts` in the third-party backend plugin exports `default`, but if there is no `export default` in the `index.ts` you will have to use `alpha.ts` instead.
*** Use `export {default} from 'THIRD_PARTY_PACKAGE/alpha'` instead of `export {default} from 'THIRD_PARTY_PACKAGE'` in such a case
====

[start=3]
. Modify `package.json` and add the following config if not already present in the file:

[source,options="nowrap"]
----
  "devDependencies": {
    "@janus-idp/cli": "^1.7.10"                         # <.>
  },
  "files": [
    "dist"                                              # <.>
  ],
  "scripts": {
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "export-dynamic": "janus-cli package export-dynamic-plugin --embed-as-dependencies --embed-package <THIRD_PARTY_PLUGIN>"   # <.>
  }
----
<.> add `@janus-idp/cli` dependency, which provides a new, required, `export-dynamic-plugin` command. _Version `1.7.10` of the janus-cli is in tech-preview at the moment. If you're unsure of using this version then use an older version, e.g. `1.7.10`_
<.> add `dist` to the package files list
<.> add `export-dynamic` to scripts. This will also embedd the dependencies as well as the third party package. _If using another version of janus-cli other than `1.7.10`, remove the `--embed-as-dependencies` argument from `export-dynamic` script_
  

==== Export the plugin for deploying to RHDH instance           [[export_backend_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn tsc
yarn export-dynamic                                                 # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                   # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
BACKEND_INTEGRITY_HASH=$(npm pack ./dist-dynamic --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Backend plugin integrity Hash: $BACKEND_INTEGRITY_HASH"  # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                      # <.>
----
<.> Export the plugin as a dynamic plugin
<.> Env variable to point to the directory that will contain the dynamic plugin tgz files
<.> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<.> Lists the directory to show you the contents of output directory


Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance        [[export_backend_plugin_local]]

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
export LOCAL_DYNAMIC_PLUGIN_ROOT_DIR=<JANUS_SHOWCASE_DIR>/dynamic-plugins-root     # <.>
yarn install
yarn tsc
yarn export-dynamic --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR    # <.>
----
<.> Environment variable to point to the local dynamic-plugin-root directory that should be in the Janus Showcase root directory
<.> Export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your showcase directory to be able to run/test it locally

[NOTE]
====
_Above commands should be run in the frontend plugin directory inside the Backstage app that is created initially_

_**Do not create the symbolic link manually as that will take the node_modules from the symlink directory instead of the showcase and can cause issues at runtime**_
====


== Dynamic custom plugin                   [[custom_dynamic_plugin]]
To convert a custom plugin into a dynamic plug, following steps have to be performed:

* Make sure the **create new app** prerequisite is met
* Add `export-dynamic` to `scripts`
* Add `janus-cli` to `devDependencies`
* Add `dist-scalprum` to `files` for frontend plugin only
* Convert the backend plugin to the new backend system

=== Dynamic Frontend custom plugin         [[custom_frontend_dynamic_plugin]]
To convert a frontend custom plugin into a dynamic plugin, complete the following step:

* Modify `package.json` and add the following config if not already present in the file:
[source]
----
  "devDependencies": {
    ...
    "@janus-idp/cli": "^1.7.10"                                   # <.>
  },
  "files": [
    "dist"
    "dist-scalprum"                                               # <.>
  ],
  "scripts": {
    ...
    "export-dynamic": "janus-cli package export-dynamic-plugin"   # <.>
  },
----
<.> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<.> add `dist-scalprum` to the package files list
<.> add `export-dynamic` to scripts


==== Export the frontend plugin for deploying to RHDH instance       [[export_frontend_custom_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn export-dynamic                                                     # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                       # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
FRONTEND_INTEGRITY_HASH=$(npm pack --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Frontend plugin integrity Hash: $FRONTEND_INTEGRITY_HASH"    # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                          # <.>
----
<.> Export the plugin as a dynamic plugin
<.> Env variable to point to the directory that will contain the dynamic plugin tgz files
<.> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<.> Lists the directory to show you the contents of output directory

Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance    [[run_local_frontend_custom_plugin]]

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands in your frontned custom plugin directory:
[source, bash]
----
export LOCAL_DYNAMIC_PLUGIN_ROOT_DIR=<JANUS_SHOWCASE_DIR>/dynamic-plugins-root    # <.>
yarn install
yarn export-dynamic --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR   # <.>

ls -l $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR
----
<.> Environment variable to point to the local dynamic-plugin-root directory that should be in the Janus Showcase root directory
<.> Export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your showcase directory to be able to run/test it locally

[NOTE]
====
_Above commands should be run in the frontned plugin directory inside the Backstage app that is created initially_

_**Do not create the symbolic link manually as that will take the node_modules from the symlink directory instead of the showcase and can cause issues at runtime**_

For configuration of the frontend plugin via app-config, the plugin name can be taken from `dist-scalprum/plugin-manifest.json` file after running `export-dynamic` script
====


'''

=== Dynamic Backend custom plugin         [[custom_backend_dynamic_plugin]]
To convert a backend custom plugin into a dynamic plugin, complete the following step:

. Modify `package.json` and add the following config if not already present in the file:
[source]
----
  "devDependencies": {
    ...
    "@janus-idp/cli": "^1.7.10"                                                           # <.>
  },
  "scripts": {
    ...
    "export-dynamic": "janus-cli package export-dynamic-plugin --embed-as-dependencies"   # <.>
  },
----
<.> add `@janus-idp/cli` as devDependency, which provides `export-dynamic-plugin` command
<.> add `export-dynamic` to scripts

[start=2]
. Follow the instructions given in <<add_dynamic_loading_entrypoint>> so that it can be exported as dynamic plugin

==== Export the backend plugin for deploying to RHDH instance       [[export_backend_custom_plugin]]

To deploy the dynamic plugin wrapper in a RHDH instance running in OCP, run the following commands _in the directory where you have code for your dynamic plugin_:

[source,bash,options="nowrap"]
----
yarn install
yarn tsc
yarn export-dynamic                                                 # <.>

DYNAMIC_PLUGIN_ROOT_DIR=/tmp/dynamic-plugins-root                   # <.>
mkdir $DYNAMIC_PLUGIN_ROOT_DIR
BACKEND_INTEGRITY_HASH=$(npm pack ./dist-dynamic --pack-destination $DYNAMIC_PLUGIN_ROOT_DIR --json | jq -r '.[0].integrity')  \
  && echo "Backend plugin integrity Hash: $BACKEND_INTEGRITY_HASH"  # <.>

ls -l $DYNAMIC_PLUGIN_ROOT_DIR                                      # <.>
----
<.> export the plugin as a dynamic plugin
<.> Env variable to point to the directory that will contain the dynamic plugin tgz files
<.> Stores the integrity hash of dynamic plugin tgz file after running `npm pack` command. This will also generate the tgz file in the `DYNAMIC_PLUGIN_ROOT_DIR` dir. Also displays the integrity hash, which will be needed later on when adding this dynamic plugin to the configMap
<.> Lists the directory to show you the contents of output directory


Deploy this dynamic plugin in OpenShift, as well as reference it in RHDH, by following the instructions at <<deploy_dynamic_plugins>>

==== Export the plugin for deploying to local Janus instance          [[export_backend_custom_plugin_local]]

To deploy the dynamic plugin wrapper in the Janus instance running locally, run the following commands:
[source, bash]
----
export LOCAL_DYNAMIC_PLUGIN_ROOT_DIR=<JANUS_SHOWCASE_DIR>/dynamic-plugins-root    # <.>
yarn install
yarn tsc
yarn export-dynamic --dev --dynamic-plugins-root $LOCAL_DYNAMIC_PLUGIN_ROOT_DIR   # <.>
----
<.> Environment variable to point to the local dynamic-plugin-root directory that should be in the Janus Showcase root directory
<.> export the plugin as a dynamic plugin and create a symbolic link to it in the `dynamic-plugins-root` directory in your showcase directory to be able to run/test it locally

[NOTE]
====
_Above commands should be run in the backned plugin directory inside the Backstage app that is created initially_

_**Do not create the symbolic link manually as that will take the node_modules from the symlink directory instead of the showcase and can cause issues at runtime**_
====


== Add dynamic loading entrypoint to Backend plugin               [[add_dynamic_loading_entrypoint]]
If a custom or third-party backend plugin is not on the new Backstage backend system, you will need to add the following code in your wrapper for the third-party plugin or to your custom backend plugin:


If a custom or third-party backend plugin is not on the new Backstage backend system, you will need to make the following changes to your backend plugin codebase:

. Create a new file named `src/plugin.ts` with the following contents:

[source, typescript]
----
import {
    coreServices,
    createBackendPlugin,
  } from '@backstage/backend-plugin-api';
  import { createRouter } from './service/router';
  
  /**
   * @YOUR_BACKEND_PLUGIN_NAME@ backend plugin                                // <.>
   *
   * @public
   */
  export const @YOUR_BACKEND_PLUGIN_NAME@Plugin = createBackendPlugin({       // <.>
    pluginId: '@YOUR_BACKEND_PLUGIN_ID@',                                     // <.>
    register(env) {
      env.registerInit({
        deps: {
          logger: coreServices.logger,
          httpRouter: coreServices.httpRouter,
          // Add any extra dependency that is used to create the router       // <.>
        },
        async init({ httpRouter, logger }) {
          httpRouter.use(
            await createRouter({
              logger
              // Add any extra parameter that is needed to create the router  // <.>
            }),
          );
        },
      });
    },
  });
----
<.> Repalce `@YOUR_BACKEND_PLUGIN_NAME@` with the name of your plugin for documentation purpose, e.g. `Hello-World`
<.> Repalce `@YOUR_BACKEND_PLUGIN_NAME@` with the name of your plugin name, e.g. `helloWorld`
<.> Replace `@YOUR_BACKEND_PLUGIN_ID@` with a unique id for your plugin, e.g. `helloWorld`
<.> Add any extra dependency that is used to create the router for your plugin, e.g. `cache: coreServices.cache`
<.> Add any extra parameters that are used to create the router for your plugin, e.g. `cacheClient: cache`

[NOTE]
====
_Template for the above code is provided at {uri-backstage-dynamic-loading-template}[Backend plugin template]. A real example is provided {uri-backstage-dynamic-loading-example}[here]_

_**Replace all the tags inside @@ with valid values**_
====

[start=2]
. Modify `src/index.ts` by adding the following code:

[source, typescript]
----
...

export { @YOUR_BACKEND_PLUGIN_ID@ as default } from './plugin';   // <.>
----
<.> `@YOUR_BACKEND_PLUGIN_ID@` is the pluginId (from `src/plugin.ts`) for your backend custom plugin or the wrapper for the third-party plugin

[NOTE]
====
_Example for the above code is provided at {uri-backstage-dynamic-loading-index}[here]_
====


== Test the dynamic plugin on OCP [[deploy_dynamic_plugins]]

To test out the dynamic plugin (irrespective of whether it is a wrapper for third-party plugin or custom plugin), follow the instructions given below.

=== Create new app for plugin registry

If these commands have already been executed earlier (for another dynamic plugin) then simply run the step given in <<refresh_registry>>

[source,bash,options="nowrap"]
----
oc project <YOUR_PROJECT_OR_NAMESPACE>
oc new-build httpd --name=plugin-registry --binary                          # <.>
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
oc new-app --image-stream=plugin-registry                                   # <.>
----
<.> Creates a new build configuration
<.> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source. _The `DYNAMIC_PLUGIN_ROOT_DIR` env variable should be set before running this command_
<.> Creates a new app using the plugin-registry build

[NOTE]
.During testing
====
. _You can set an environment variable `SKIP_INTEGRITY_CHECK=true` if you prefer to not use the integrity hash, or want to quickly test changes in your plugin._
. _Setting `integrity` for the dynamic plugin can be skipped once this environment variable is set_
====


'''

=== Update dynamic plugin configMap

Modify the dynamic plugins configMap by adding the following config:
[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      <EXISTING_DYNAMIC_PLUGINS>
      - package: 'http://plugin-registry:8080/<NAME_OF_YOUR_DYNAMIC_PLUGIN_N_VERSION>.tgz'    # <.>
        disabled: false
        integrity: '<INTEGRITY_HASH_VALUE_FROM_npm_pack_command>'                             # <.>
        pluginConfig:
          dynamicPlugins:
            frontend:                                                                         # <.>
              <NAME_OF_YOUR_DYNAMIC_PLUGIN>:                                                  # <.>
                dynamicRoutes:
                  - importName: <THIRD_PARTY_COMPONENT>                                       # <.>
                    menuItem:
                      text: <THIRD_PARTY_>                                                    # <.>
                    path: /<UNIQUE_PATH>                                                      # <.>
----
<.> <WrapperPluginName>-<WrapperPluginVersion>.tgz - file that was created with `npm pack` command (prefixed with `http://plugin-registry:8080` - this is where the plugin-registry app is running)
<.> Integrity hash generated from `npm pack` output
<.> Configuration for the third-party frontned plugin
<.> Name of the wrapper plugin
<.> Component name of the third party plugin. Defauls to the `export` in index.ts
<.> Sidebar menu item text
<.> Unique path in the app

'''

=== Refresh plugin registry    [[refresh_registry]]

For any updates to this plugin, or if you add more dynamic plugins, run the following command:

[source,bash,options="nowrap"]
----
oc start-build plugin-registry --from-dir=$DYNAMIC_PLUGIN_ROOT_DIR --wait   # <.>
----
<.> Starts a new build for plugin-registry using the `DYNAMIC_PLUGIN_ROOT_DIR` dir as the source


== Local testing configuration

For testing the dynamic plugins locally, follow the instructions given below.

Add the following config to `app-config.local.yaml` to allow dynamic plugins to be read and configured for local testing:

[source, yaml]
----
app:                                                                                                                           
  title: Janus IDP Backstage Showcase - Dynamic plugins
  baseUrl: http://localhost:3000

proxy:
 skipInvalidProxies: true
 endpoints: {}

dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    <FRONTEND_DYNAMIC_PLUGIN_NAME>:
      dynamicRoutes:
        - importName: <THIRD_PARTY_PLUGIN_COMPONENT>
          menuItem:
            text: "<TEXT_2_DISPLAY_IN_SIDEBAR>"
            icon: "<ICON_FOR_MENU_IN_SIDEBAR>"
          path: /<UNIQUE_PATH>
...
...
----

Configuration for most of the backend plugins will go in the above config yaml but in their own respective sections.


== Using icons with frontend plugins

Follow the steps given below to use the custom icons for your frontend plugins:

. Export the icon in your plugin as shown below:

[source, typescript]
----
export { default as fancyIcon } from '@material-ui/icons/<SOME_FANCY_ICON>';      // <.>
----
<.> The icon is exported as `fancyIcon`

[start=2]
. Add a reference to the exported icon in  `app-config` yaml file, as shown below:

.. RHDH configuration

[source, yaml]
----
    # ...
    # Existing dynamic packages
    # ...

    - package: <Location_of_plugin>
      disabled: false
      integrity: '<HASH_VALUE>'
      pluginConfig:
        dynamicPLugins:
          frontend:
            <FRONTEND_DYNAMIC_PLUGIN_NAME>:
              appIcons:
               - name: textNameForTheFancyIcon      # <.>
                 importName: fancyIcon              # <.>
              dynamicRoutes:
                - importName: <IMPORTED_COMPONENT>
                  menuItem:
                    text: <MENU_TEXT>
                    icon: textNameForTheFancyIcon   # <.>
              mountPoints:
                ...
----


[start=2]
.. Local configuration

[source, yaml]
----
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    <FRONTEND_DYNAMIC_PLUGIN_NAME>:
      appIcons:
        - name: textNameForTheFancyIcon     # <.>
          importName: fancyIcon             # <.>
      dynamicRoutes:
        - importName: <IMPORTED_COMPONENT>
          menuItem:
            text: <MENU_TEXT>
            icon: textNameForTheFancyIcon   # <.>
      ...
      mountPoints:
      ...
      ...
----
<.> Icon name to be used in `menuItem`
<.> Custom icon that has been exported as `fancyIcon`
<.> Use the menu name defined earlier in (1)

[NOTE]
====
. _{uri-icons-systen-internal}[Backstage system icons] can be used without any extra exports. To use the system icons, simply add them to the `app-config` yaml as shown above._

. Check the following files for the use of custom and system icons:
.. {uri-custom-icon-exported-ex}[Export custom icon]
.. {uri-custom-icon-use-ex-1}[Custom icon text name]
.. {uri-custom-icon-use-ex-2}[Custom icon exported name]
.. {uri-custom-icon-use-ex-3}[Reference custom icon]
.. {uri-system-icon-use-ex}[Reference system icon]
====


== References

* {uri-dynamic-plugins}[RHDH - Dynamic plugin doc] +
* {uri-mountpoints}[RHDH - Dynamic plugin - mountpoints example] +
* {uri-rhdh-mountpoints}[RHDH - Dynamic plugin - available mountpoints] +
* {uri-backstage-new-backend-system}[Backstage new backend system] +
* {uri-backstage-create-new-app}[Backstage - create new app] +
* {uri-backstage-create-new-version}[Backstage - create new app version (compatible with RHDH 1.1)] +
* {uri-janus-backstage-version}[RHDH 1.1 - backstage version] +
* {uri-icons-systen-internal}[Backstage system icons] +
* {uri-icons}[RHDH - extend available icons] +
