= RHDH dynamic plugins

This directory contains starter files to create a dynamic plugin wrapper for third-party frontend plugin

:icons: font
:uri-dynamic-plugin-readme: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/readme.adoc#export_frontend_plugin
:uri-setup-script: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins/starters/setup-wrapper.sh

== Plugin wrapper for frontend plugin

To create a dynamic plugin wrapper for third-party frontend plugin, copy the files and directories from this direcoty to an empty directory, and either run {uri-setup-script}[setup-wrapper.sh] or follow these stpes to change the files in the new directory:

[NOTE]
The script `setup-backend.sh` can be run without any arguments to see its usage.

* Replace the `<THIRD_PARTY_PLUGIN>` in `src/index.ts` with correct third-party plugin
* Copy `package.json.template` to `package.json`
* Replace the following with correct values, in `package.json`:
```
  "name": "@THIRD_PARTY_PLUGIN_WITHOUT_SCOPE@-wrapper",                           # <.>
  "description": "Wrapper for @THIRD_PARTY_PLUGIN_SHORT_NAME@ frontend plugin",   # <.>
  "author": "@AUTHOR@",                                                           # <.>
  "dependencies": {
    "@THIRD_PARTY_PLUGIN_WITH_SCOPE@": "@THIRD_PARTY_PLUGIN_VERSION@"             # <.>
```
<1> Replace with your plugin name
<2> Replace with correct description for your plugin
<3> Replace with correct author name
<4> Replace with the third-party plugin and its version


Once the above changes are complete, please follow the instructions in {uri-dynamic-plugin-readme}[Dynamic Plugins readme] to complete the configuration and installation of this dynamic plugin wrapper.
