= Dynamic wrapper for Bazaar plugin
:icons: font
:note-caption: :information_source:
:uri-bazaar: https://github.com/backstage/backstage/tree/v1.23.4/plugins/bazaar
:uri-app-config: https://github.com/sgahlot/rhdh-op-config/blob/main/dynamic-plugins/samples/wrapper-frontend/bazaar/app-config-bazaar.yaml
:uri-export-frontend-plugin: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins#export_frontend_plugin
:uri-export-frontend-plugin-local: https://github.com/sgahlot/rhdh-op-config/tree/main/dynamic-plugins#export_frontend_plugin_local

This directory contains files to create a dynamic plugin wrapper for the {uri-bazaar}[Bazaar] plugin

== Steps

To create a dynamic plugin wrapper for Bazaar plugin, copy the files present in this directory in a local directory and run the following commands:

[source="bash",options="nowrap"]
----
  yarn install
  yarn export-dynamic
----

This wrapper can be tested in RHDH or locally. To test it, following steps should be performed:

. To test in RHDH instance
** Follow {uri-export-frontend-plugin}[these instructions] to export this dynamic wrapper
** Add the following content to a configMap:

[source="yaml",options="nowrap"]
----
# RHDH configuration
# Frontned plugin configuration: provides the Bazaar information in the "Overview" tab as well as from a link in the Sidebar
  plugins:
    # ...
    # Existing dynamic packages
    # ...

    - package: '<Location_of_bazaar_wrapper>'
      disabled: false
      integrity: 'BAZAAR_WRAPPER_HASH'
      pluginConfig:
        dynamicPlugins:
          frontend:
            bazaar-wrapper:
              appIcons:
                - name: bazaarStorefrontIcon                      # <.>
                  importName: StorefrontIcon                      # <.>            
              dynamicRoutes:
                - importName: BazaarPage
                  menuItem:
                    text: Bazaar
                    icon: bazaarStorefrontIcon                    # <.>
                  path: /bazaar
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: BazaarOverviewCard
                  config:
                    layout:
                      gridColumn: "1 / -1"
                      width: 50vw
----
<.> Icon name to be used in menuItem
<.> Icon name that was exported in the plugin wrapper
<.> Same name as defined earlier in (1)

[start=2]
. To test in Janus local instance
** Follow {uri-export-frontend-plugin-local}[these instructions] to export this dynamic wrapper
** Add the following content to app-config yaml:

[source="yaml",options="nowrap"]
----
# Frontned plugin configuration: provides the Bazaar information in the "Overview" tab as well as from a link in the Sidebar
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    bazaar-wrapper:
      appIcons:
        - name: bazaarStorefrontIcon                      # <.>
          importName: StorefrontIcon                      # <.>
      dynamicRoutes:
        - importName: BazaarPage
          menuItem:
            text: Bazaar
            icon: bazaarStorefrontIcon                    # <.>
          path: /bazaar
      mountPoints:
        - mountPoint: entity.page.overview/cards
          importName: BazaarOverviewCard
          config:
            layout:
              gridColumn: "1 / -1"
              width: 50vw
----
<.> Icon name to be used in menuItem
<.> Icon name that was exported in the plugin wrapper
<.> Same name as defined earlier in (1)

After the restart of RHDH (or Janus local), you should see the Bazaar contents in the **Overview** tab of your entity as well as using the Sidebar link.

[NOTE]
====
_**The config provided above is also given in {uri-app-config}[Bazaar app config]**_
====